name: clang-format Check

on: [push, pull_request]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'src'
            exclude: ''              # Nothing to exclude
          - check: 'include'
            exclude: 'exprtk.hpp'    # Exclude file
          - check: 'test'
            exclude: ''              # Nothing to exclude
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Mozilla' # optional
