name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: ["labrobotica/wolf_deps:18.04", "labrobotica/wolf_deps:20.04", "labrobotica/wolf_deps:22.04"]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@main
    - run: |
        mkdir -pv build_${{matrix.build_type}}
        cd build_${{matrix.build_type}}
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..
        make -j2
        ctest -j2

