name: CI

on: [push, pull_request, workflow_dispatch]
  
permissions: read-all

defaults:
  run:
    shell: bash
    
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        build_type: [Debug, Release]
        cxx_standard: [11, 14, 17, 20]
        yaml_cpp_version: [yaml-cpp-0.6.0, yaml-cpp-0.6.1, yaml-cpp-0.6.2, yaml-cpp-0.6.3, yaml-cpp-0.7.0, master]

    steps:
    
    - name: dependencies
      run: |
        sudo apt install libboost-filesystem-dev libeigen3-dev -y
        
    - name: install yaml-cpp
      run: |
        git clone -b ${{matrix.yaml_cpp_version}} --depth 1 https://github.com/jbeder/yaml-cpp.git
        mkdir -pv yaml-cpp/build
        cd yaml-cpp/build
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DYAML_BUILD_SHARED_LIBS=ON -DBUILD_SHARED_LIBS=ON -DYAML_CPP_BUILD_TESTS=OFF ..
        make -j2
        sudo make install
        
    - uses: actions/checkout@v4
    
    - name: Configure
      run: |
        cmake \
          -S "${{ github.workspace }}" \
          -B build \
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} \
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -D BUILD_TESTS=ON

    - name: Build
      run: |
        cmake \
          --build build \
          --config ${{ matrix.build_type }} \
          --parallel

    - name: Run Tests
      shell: bash
      run: |
        ctest \
          --test-dir build \
          --build-config ${{ matrix.build_type }} \
          --output-on-failure
