name: CI

on: [push, pull_request, workflow_dispatch]
  
permissions: read-all

defaults:
  run:
    shell: bash
    
jobs:
  build_and_test:
    runs-on: "ubuntu-latest"
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: [ubuntu:18.04, ubuntu:20.04, ubuntu:22.04, ubuntu:24.04]
        build_type: [Debug, Release]
        cxx_standard: [11, 14, 17, 20]
        yaml_cpp_version: [yaml-cpp-0.7.0, master]

    steps:

    - name: dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt install cmake build-essential git libboost-filesystem-dev libeigen3-dev -y
        
    - name: install yaml-cpp
      run: |
        git clone -b ${{matrix.yaml_cpp_version}} --depth 1 https://github.com/jbeder/yaml-cpp.git
        mkdir -pv yaml-cpp/build
        cd yaml-cpp/build
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCXX_STANDARD=${{ matrix.cxx_standard }} -DYAML_BUILD_SHARED_LIBS=ON -DYAML_CPP_BUILD_TESTS=OFF ..
        make -j2
        make install
        
    - uses: actions/checkout@v4
    
    - name: build
      run: |
        pwd
        ls
        mkdir -pv build
        cd build
        cmake -DCXX_STANDARD=${{ matrix.cxx_standard }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON ..
        make -j2
        ctest -j2 --output-on-failure

    - name: Tests
      run: |
        ctest --output-on-failure
